/// <reference types="Cypress" />


describe('SocialPie-login',function()
{
    //1
    it('To verify that user should be able to enter the organization name',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)
    cy.get("[type='text']").first().type('Aisha')
    cy.get("[type='text']").should("be.enabled")
    }) 

   // 2
    it('To verify that user should be able to enter the Country',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)
    cy.get('#mat-select-0').click()
    const country = cy.get('#mat-option-1').should('be.visible')
    country.click()
}) 
    //3
    it('To verify that user should be able to enter the Address',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)
    cy.get('input[name="address"]').should('exist')
}) 

    //4
    it('To verify that user should be able to enter the Phone Number',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)
    cy.get('input[name="phone"]').should('exist')
}) 

5
    it('To verify that user should be able to enter the valid Phone No.',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)
    cy.get("[type='text']").first().type('TMKUC')
    cy.get('#mat-select-0').click()
    const country = cy.get('#mat-option-1').should('be.visible')
    country.click()
    const address = cy.get('input[name="address"]').should('exist')
    address.type('PIDC ')
    const phone = cy.get('input[name="phone"]').should('exist')
    phone.type('+92123456789')
    const submit = cy.get('.mat-button-wrapper').contains(' Create Organization ').and('be.visible')
    }) 

    //6
    it('To verify that user should not be able to create organization without leaving any field',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    cy.wait(10000)

    cy.get('#mat-select-0').click()
    const country = cy.get('#mat-option-1').should('be.visible')
    country.click()
    const address = cy.get('input[name="address"]').should('exist')
    address.type('PIDC ')
    const phone = cy.get('input[name="phone"]').should('exist')
    phone.type('+92123456789')
    cy.get('.mat-button-wrapper').contains(' Create Organization ').and('exist');
    }) 

    //9
    it('To verify that user should be able to redirect on organization page after entering the username first time',function()
    {
    cy.visit('https://app.socialpie.io:7804/session/signin')
    cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
    cy.get('[id=username]').click()
    cy.get('[id=username]').type('jollyllb@mailinator.com')
    cy.get('[id=password]').type('Paramount23?')
    const button = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
    button.click()
    }) 

     //7
     it('To verify that user should be able to create organization in one account',function()
     {
     cy.visit('https://app.socialpie.io:7804/session/signin')
     cy.get('[id=username]').should("be.visible").and('be.enabled').and('exist')
     cy.get('[id=password]').should("be.visible").and('be.enabled').and('exist')
     cy.get('[id=username]').click()
     cy.get('[id=username]').type('jollyllb@mailinator.com')
     cy.get('[id=password]').type('Paramount23?')
     const buttn = cy.get('[type="submit"]').should('be.visible').and('not.be.disabled')
     buttn.click()
     cy.wait(20000)
     cy.get("[type='text']").first().type('TMKUC Sub')
     cy.get('#mat-select-0').click()
     const country = cy.get('#mat-option-1').should('be.visible')
     country.click()
     const address = cy.get('input[name="address"]').should('exist')
     address.type('PIDC Saddar Karachi ')
     const phone = cy.get('input[name="phone"]').should('exist')
     phone.type('+92123456777')
     const button = cy.get('.mat-button-wrapper').contains(' Create Organization ').and('exist')
     button.click()
     cy.wait(12000)
     cy.get('.mat-button-wrapper').contains(' See Plans ').and('exist')
     })
})